package com.example.TP_Pirmas.mybatis.model;

import java.util.Date;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT.ID
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT.END_DATE
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT.NAME
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT.START_DATE
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT.TYPE
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT.ID
     *
     * @return the value of PUBLIC.PROJECT.ID
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT.ID
     *
     * @param id the value for PUBLIC.PROJECT.ID
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT.END_DATE
     *
     * @return the value of PUBLIC.PROJECT.END_DATE
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT.END_DATE
     *
     * @param endDate the value for PUBLIC.PROJECT.END_DATE
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT.NAME
     *
     * @return the value of PUBLIC.PROJECT.NAME
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT.NAME
     *
     * @param name the value for PUBLIC.PROJECT.NAME
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT.START_DATE
     *
     * @return the value of PUBLIC.PROJECT.START_DATE
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT.START_DATE
     *
     * @param startDate the value for PUBLIC.PROJECT.START_DATE
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT.TYPE
     *
     * @return the value of PUBLIC.PROJECT.TYPE
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT.TYPE
     *
     * @param type the value for PUBLIC.PROJECT.TYPE
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }
}