package com.example.TP_Pirmas.mybatis.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.ID
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.EMAIL
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.USERNAME
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.ID
     *
     * @return the value of PUBLIC.USER.ID
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.ID
     *
     * @param id the value for PUBLIC.USER.ID
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.EMAIL
     *
     * @return the value of PUBLIC.USER.EMAIL
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.EMAIL
     *
     * @param email the value for PUBLIC.USER.EMAIL
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.USERNAME
     *
     * @return the value of PUBLIC.USER.USERNAME
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.USERNAME
     *
     * @param username the value for PUBLIC.USER.USERNAME
     *
     * @mbg.generated Tue Mar 30 19:53:55 EEST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }
}